bug: Include empty string check for permission resource
Currently, if we pass empty string for resource, the
"capitalize_first_letter" check panics, because it misses the empty
string check looks like.

```
File "/home/kavi/src/play-weaviate/venv/lib/python3.13/site-packages/weaviate/util.py", line 412, in _capitalize_first_letter
    return string[0].capitalize() + string[1:]
           ~~~~~~^^^
IndexError: string index out of range
```

Signed-off-by: Kaviraj <kavirajkanagaraj@gmail.com>